version: '2'

services:  
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    container_name: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ../src/LicenseManager.csproj && dotnet publish ../src/LicenseManager.csproj -c Docker -o ./build"