FROM microsoft/dotnet:runtime
WORKDIR /dotnetapp
COPY ./bin/Docker/netcoreapp2.0/publish .
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT production
ENTRYPOINT dotnet LicenseManager.Api.dll